### ISSUE TITLE
有创意的工作

### ISSUE THREAD

**Issue by zyl1042919014** [USTC3DV/FlashAvatar-code#11]
您好，请问复现代码时landmark_embedding.npy文件该从哪获取，非常感谢

**Comment by Tiandishihua** [comment]
> 您好，请问复现代码时landmark_embedding.npy文件该从哪获取，非常感谢

您好！请问跑通了metrical-tracker算法吗？谢谢

**Comment by zyl1042919014** [comment]
> > 您好，请问复现代码时landmark_embedding.npy文件该从哪获取，非常感谢
> 
> 您好！请问跑通了metrical-tracker算法吗？谢谢

跑通了

**Comment by xiangjun-xj** [comment]
> 您好，请问复现代码时landmark_embedding.npy文件该从哪获取，非常感谢

它在本仓库flame文件夹里
