### ISSUE TITLE
For  metrical-tracker

### ISSUE THREAD

**Issue by Tiandishihua** [USTC3DV/FlashAvatar-code#13]
In metrical-tracker,
lmk_path = imagepath.replace('images', 'kpt').replace('.png', '.npy').replace('.jpg', '.npy') is kpt7.npy ?
lmk_path_dense = imagepath.replace('images', 'kpt_dense').replace('.png', '.npy').replace('.jpg', '.npy') is kpt68.npy?

**Comment by xiangjun-xj** [comment]
Not really. 'kpt' and 'kpt_dense' are folder names under 'input/<id_name>/', which will be generated during the tracking process. I don't konw the exact reason why you can't run metrical-tracker and you should turn to its issues to find some clues.

**Comment by superhero177** [comment]
Hello, @Tiandishihua  , Excuse me，
Have you solved this problem?
