### ISSUE TITLE
generic_model.pkl is not found!

### ISSUE THREAD

**Issue by SuiXiaoDou** [USTC3DV/FlashAvatar-code#14]
Hello author, thank you very much for providing such a wonderful project. 
1. When I was trying to learn your project: When I run train.py 
`python train.py --idname example/dataset/Obama`
 I find that there is no `flame/generic_model.pkl` file, I would like to ask if this is not found or not uploaded. 
 
![image](https://github.com/USTC3DV/FlashAvatar-code/assets/108884031/a05feccb-c31a-41eb-b432-74fc2d52e56d)

 2. I run the test.py 
 `python test.py -- idname example/dataset/Obama -- checkpoint example/dataset/Obama/log/ckpt/chkpt.pth`
  I did not find the same file.
  
![image](https://github.com/USTC3DV/FlashAvatar-code/assets/108884031/2be9acf7-076e-41fc-aa1f-1bd3bb3f30c2)

   Could you please help me? Thank you very much

**Comment by xiangjun-xj** [comment]
Please take a look at [#8](https://github.com/USTC3DV/FlashAvatar-code/issues/8#issue-2237143262)
