### ISSUE TITLE
请教一些论文细节，非常感谢

### ISSUE THREAD

**Issue by 3Der1999** [USTC3DV/FlashAvatar-code#15]
您好，非常感谢项目的开源。我在阅读论文时遇到一些问题，可否请您解答一下：
1.论文中提到`When expression changes, the corresponding 3D position
of Gaussians can be obtained by weighting vertex coordinates using fixed barycentric coordinates`，这是handle表情变化的情况。那flame pose改变时（比如人扭头），如果UV map不变，和UV map绑定的GS是不是就和Flame模型的顶点对不上了？
2.在Sec4.2开头，`We denote the centers of mesh-attached Gaussians as µ_M
and corresponding positions on canonical mesh µ_T.` 请问这里的µ<sub>T</sub>是什么，是uv map上和µ<sub>M</sub>距离最近的点所对应的Flame顶点吗？

**Comment by xiangjun-xj** [comment]
1. Change of flame pose won't influence the mesh topology and  UV correspondence.
2. In our settings, "canonical" means neutral expression.
