### ISSUE TITLE
Which Face-Parsing code was used to produce parsing directory in Obama example?

### ISSUE THREAD

**Issue by ankit-gahlawat-007** [USTC3DV/FlashAvatar-code#16]
Hello, 

Could you point out to which repository or library did you use for face parsing (mouth and neckhead)?
The paper mentions the use of BiSeNet V2 framework, but I am not able to figure out which is the exact code which was used to produce the outputs.

I tried using dg-face-parsing (https://pypi.org/project/dg-face-parsing/) but it would require processing to exactly get the mouth and neckhead images as for Obama example.

Thank You

**Comment by xiangjun-xj** [comment]
You can try https://github.com/zllrunning/face-parsing.PyTorch.
