### ISSUE TITLE
About paper content

### ISSUE THREAD

**Issue by buptzz** [USTC3DV/FlashAvatar-code#17]
Hello, I have read your paper, and I understand that you control the actions based on the expression coefficients of FLAME. However, from my understanding, these coefficients do not include descriptions of jaw/lip movements. Could you please explain what controls these particular actions?

**Comment by xiangjun-xj** [comment]
The expression code we use includes expression coefficients and jaw pose. But of course it is still hard to control extremely slight motions, which are not well tracked.
