### ISSUE TITLE
CUDA out of memory. Tried to allocate 21355.80 GiB.

### ISSUE THREAD

**Issue by liaopuyun** [USTC3DV/FlashAvatar-code#18]
Great work! Can't wait to run it on my own data.

I run the script test.py but find it require overmuch CUDA memory when render the gaussian.
I try to render with the first 100 points, or decrease the fov by 100 times, yet it makes not much difference.
How can I figure out what is going on?

**Comment by xiangjun-xj** [comment]
Someone else has successfully run the code, so I believe the script test.py itself is right. Maybe you should check places you changed. 
The main memory cost is from images loaded in the test dataset, you can load paths instead. But I think this is not the point.

**Comment by liaopuyun** [comment]
Thank you for your kindly answer.
I carefully checked the code and make sure there is no change.
So I viewed the cuda code in diff-gaussian-rasterization. In the code rasterizer_impl.cu, I found no mater how many gaussian I input, the `num_rendered` in line 282 is always 393217, and the  `binning.sorting_size` in line 192 is always about 20000G.
What is that supposed to mean?

**Comment by xiangjun-xj** [comment]
Sorry to say that I have no idea. What about creating the environment again.
