### ISSUE TITLE
FLAME parameters

### ISSUE THREAD

**Issue by lgelecji** [USTC3DV/FlashAvatar-code#19]
Hello,

I tried to use my own image as input. So I've used MICA for extracing FLAME parameters. However, I could not match output of FLAME parameter of MICA to FLAME parameter of FlashAvatar.
As fas as I know,
MICA extracts FLAME parameters: identity.npy (300 real numbers which might be 'shape'), kpt7.npy (7 x 3 = 21 real numbers), kpt68.npy (68 x 3 = 204 real numbers)
and FLAME parameter of FlashAvatar are ['exp' 100 real numbers, 'shape' 300 real numbers,  'tex' 140 real numbers, 'sh' 27 real numbers , 'eyes' 12 real numbers, 'eyelids' 2 real numbers, 'jaw' 6 real numbers]
Please let me know what I've done wrong. Thank you.

**Comment by xiangjun-xj** [comment]
Try [metrical-tracker](https://github.com/Zielon/metrical-tracker) to get FLAME parameters.

**Comment by lgelecji** [comment]
Thanks for your help. it worked!
