### ISSUE TITLE
Is it applicable for facial expression recognition tasks

### ISSUE THREAD

**Issue by Mysterious-handsome-man** [USTC3DV/FlashAvatar-code#2]
Impressive work! May I ask if this work can be used for obtaining dynamic 3D facial videos (RGBD video) from monocular video input (RGB video), and using the output RGB and 3D information for facial expression recognition tasks?

**Comment by xiangjun-xj** [comment]
We are not sure about your question. As you can see, we are more concerned with the rendering results and cannot guarantee the quality of depth and geometry.

**Comment by Mysterious-handsome-man** [comment]
Thank you very much for your reply! As we have a depth camera, we are also exploring the integration of depth information into 3D GS for more accurate results, such as precise facial 3D modeling for subsequent facial expression recognition. Do you know of any projects that are based on RGBD for 3D reconstruction? If possible, could you please recommend some to me?
Anyway，thank you for your excellent work and enthusiastic response！
