### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by tangjiapeng** [USTC3DV/FlashAvatar-code#20]
Cool work! 

If I wanna test on my own sequences, how should I preprocess the video sequences to obtain alpha maps, semantic segmentation, and MICA tracking results?

**Comment by xiangjun-xj** [comment]
> Cool work!
> 
> If I wanna test on my own sequences, how should I preprocess the video sequences to obtain alpha maps, semantic segmentation, and MICA tracking results?

You could use RVM, [face-parsing](https://github.com/zllrunning/face-parsing.PyTorch) and [metrical-tracker](https://github.com/Zielon/metrical-tracker).

**Comment by choos11** [comment]
Cool work,but what is RVM,could you please give me a link?

**Comment by bamboosteam** [comment]
Probably this. https://github.com/PeterL1n/RobustVideoMatting
Dear authors, please let me know if it's wrong.
