### ISSUE TITLE
Is the code use the wrong transpose?

### ISSUE THREAD

**Issue by aixiaodewugege** [USTC3DV/FlashAvatar-code#21]
I notice that the transpose of the mesh in first iteration is wrong. So is the code have problem handling the T?
![image](https://github.com/USTC3DV/FlashAvatar-code/assets/47085237/2f19dafb-567e-4d0a-ac4e-acc2d988e3bd)

**Comment by xiangjun-xj** [comment]
Not really. I think the reason is  that we add Gaussian offset, which has not been optimized in first iteration.

**Comment by ankarako** [comment]
I can confirm that this is indeed coming from the result of deformNet. If you initialize the output layer with zeros, you'll see the correct result
