### ISSUE TITLE
The result begins to corrupt around 140,000 iterations.

### ISSUE THREAD

**Issue by aixiaodewugege** [USTC3DV/FlashAvatar-code#22]
![image](https://github.com/USTC3DV/FlashAvatar-code/assets/47085237/088e648e-cf58-4c7b-9c69-5b2576b3eb4b)
What is the reason?

**Comment by xiangjun-xj** [comment]
Yes, this happens occasionally. 
Methods like learning rate decay may help stablize the training process. And adding more regularization term on Gaussians like scaling should help. A direct way is to reduce iteration number as earlier result is good enough. If you find the exact reason or solution, please let us know.

**Comment by aixiaodewugege** [comment]
I think it is because the different learning rate decay between gaussian model and deformation model. Is that reasonable?
