### ISSUE TITLE
Densification and motivation

### ISSUE THREAD

**Issue by xubaixinxbx** [USTC3DV/FlashAvatar-code#24]
Congrats on the paper accepted by CVPR'24 and thanks for your effort on the great work.

I would like to know,
1)  how about the performance if enabling densification in GS above the UV-sampling used in the paper,  Tab.2 only shows the different number of sampling points ( I guess here the densification is disabled, right?)  
2) the claim and the results are confusing me,  vertices init generates more GS in the detailed region like eye-balls and ears(Fig.2), but the visual performance is worse than the few sampling (UV-sampling) in Fig.10.
 ( sampling on the UV space is more "uniform" than the mesh surface, how about uniform sampling on the mesh surface? like [trimesh.sample.sample_surface_even](https://trimesh.org/trimesh.sample.html)) While Fig.10 cant fully convince me, as you report the number of GS is different based on the UV-sampling(13453 for 128 in tab.2) and vertice init(~5k in fig.2)

Thanks for clarifying again.

Best regards,
Baixin

**Comment by xiangjun-xj** [comment]
First thank you for your attention to our work. As you can see, we try to guarantee speed, quality and flexibility.
Most of your concerns are explained in the main paper, like the fifth paragraph in section1, "Analysis" in section 3 and "Surface Embedding Methods" in section 5.5. 
It is hard to fully explain why vertices init has relatively poor performance. But another possible reason is that the Gaussian position is not fully surface-attached and we add Gaussian offset as well, uneven and convex vertices init needs more complex deformation, which is hard to learn.  Also, in Fig. 10, 3348 for 64 is less than 5K.
