### ISSUE TITLE
About the UV Sampling

### ISSUE THREAD

**Issue by oceansuns** [USTC3DV/FlashAvatar-code#25]
Amazing work!

As the paper described: "It is worth noting that we add additional faces to close the mouth cavity since original
FLAME mesh does not model interior mouth (see Fig. 4)." 

So, where is the corresponding code?

**Comment by xiangjun-xj** [comment]
Thanks. The mesh we provided has already been processed.

**Comment by oceansuns** [comment]
Can you explain how it was handled?

**Comment by xiangjun-xj** [comment]
> Can you explain how it was handled?

You can use Blender to do it.
