### ISSUE TITLE
how to improve performance

### ISSUE THREAD

**Issue by blacksino** [USTC3DV/FlashAvatar-code#27]
Hello,Just followed your instructions and build an avatar on my custom dataset.
And the results seems to be not good,could you give me some advice to improve the quality?

https://github.com/USTC3DV/FlashAvatar-code/assets/44363764/176784fa-3c32-466d-b409-7e730a15ad8d

https://github.com/USTC3DV/FlashAvatar-code/assets/44363764/afa44f0f-10c2-41ab-b9f3-4f059e362765

It tooks about 5000 images including various poses and expressions to train this avatar and flame params was captured using metrical-trackers.
And I have used relative expression for reenactment.

**Comment by xiangjun-xj** [comment]
Sorry for less than ideal rendering results and tansfer results.
To improve the result, you can try better segmentation and higher Gaussian sampling density. And expression transfer, which is fluenced by both choice of neutral expression frame and decoupling capability of tracking, is indeed difficult.
Definitely we need to update the code to make the method more robust, like adding more losses and using better segmentation and tracking.

**Comment by Dylan-nalyD** [comment]
Hello, how did you make your second video? Which command did you run? How do you make one person's facial expression match another's?
