### ISSUE TITLE
When i run the test.py i got a problem

### ISSUE THREAD

**Issue by yahui-lee** [USTC3DV/FlashAvatar-code#28]
Thanks for your great work. nowdays, i run the test.py with the dataset you give( the Obama dataset) and i got an error like following screenshot. 
![QQ截图20240625105728](https://github.com/USTC3DV/FlashAvatar-code/assets/102016664/5ed0909c-9102-4ac1-9cd7-822cccc1a714)
what can  i do to solve it?

**Comment by xiangjun-xj** [comment]
Well, you need to download corresponding file from official FLAME website first and place them in the right place.
