### ISSUE TITLE
Point Cloud or Mesh extraction

### ISSUE THREAD

**Issue by Zvyozdo4ka** [USTC3DV/FlashAvatar-code#3]
Hello.
Thanks for publishing your work

I have a question regarding the outputs. Would it be possible to get rendered point cloud or mesh? 
And which coordinate system do you employ? Would it be the same as flame, and the center would be at (0,0,0) ?

**Comment by xiangjun-xj** [comment]
We inherit the same structure as 3D Gaussian Splatting, and you can get rendered point cloud or mesh following other 3DGS-based works like DreamGaussian for example.
As for the coordinate system, ours is the same as MICA, which may be a little (very little) different from original FLAME and is transferred to 3DGS's system in [https://github.com/USTC3DV/FlashAvatar-code/blob/ef1823b944cec9bd968b5830032fc434deaaf2ee/scene/__init__.py#L70](url)
