### ISSUE TITLE
an issue with setting environment 

### ISSUE THREAD

**Issue by Zvyozdo4ka** [USTC3DV/FlashAvatar-code#4]
Hello.

Have you encountered problems with installation of diff-gaussian-raterization?

I tried manually to install all packages, but only `pip install submodules/diff-gaussian-rasterization ` did not work.

If you solved this problem, or know how to solve it, please explain.

Thank you

**Comment by xiangjun-xj** [comment]
Generally, "conda env create --file environment.yml" will help you to install diff-gaussian-raterization. 
Otherwise, "cd submodules/diff-gaussian-rasterization & pip install -e ." may help.

**Comment by Zvyozdo4ka** [comment]
> Generally, "conda env create --file environment.yml" will help you to install diff-gaussian-raterization. Otherwise, "cd submodules/diff-gaussian-rasterization & pip install -e ." may help.

i did as you mentioned, also i downloaded again by `git clone --recurse-submodules https://github.com/USTC3DV/FlashAvatar-code.git`, then `git checkout main`, but neither your instruction, nor  `conda env create --file environment.yml` worked out. 

Also i downloaded from ` git clone https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
` and again `pip install -e .` did not work. 

Do you have any idea, how to resolve this issue?

**Comment by xiangjun-xj** [comment]
Well, sorry to say that I have no idea. Maybe you should try to install the environment of original 3DGS first to find some clues. 
(One possible reason: diff-gaussian-rasterization has its own submodule which should be git-clonned if you install all packages manually.)

**Comment by Zvyozdo4ka** [comment]
@xiangjun-xj I do not know what to do either... At least thank you for your responses so much! 

Could you share your cuda version?

**Comment by xiangjun-xj** [comment]
> @xiangjun-xj I do not know what to do either... At least thank you for your responses so much!
> 
> Could you share your cuda version?

11.7
